/**
 * Created by semanticbits on 22/9/16.
 */
(function(){
    angular.module('CommonSpace',[
        'CommonSpace.user',
        'CommonSpace.topics',
        'CommonSpace.answer',
        'CommonSpace.question',
        'CommonSpace.component',
        'ui.router',
        'ui.bootstrap',
        'ui.router.modal',
        '720kb.datepicker',
        'ngResource',
        'angular-input-stars',
        'ngStorage',
        'angular-loading-bar',
        'ngCookies',
        'mm.acl'
    ]);
}());
